### ISSUE TITLE
Pattern Library 

### ISSUE THREAD

**Issue by fakeha-abdullah** [webdev6/obscure-book-genres#30]
- [x] Finishing off our pattern library.

**Comment by catherine9** [comment]
The pattern library is only missing two things, the favourites and bookmarks. The rest are there however they need to be fixed since most either don't match the layout at all or they do and it's just minor tweaks. Images and non lorem ipsom texts are still missing however it is unclear what kind of photos and text we will be using unless we are just sticking to lorem ipsom.
